#[derive(Debug, Default)]
pub(crate) struct XwaylandMetrics {
    pub(crate) state_transitions: u64,
    pub(crate) generations_started: u64,
    pub(crate) lazy_triggers: u64,
    pub(crate) startup_duration_ns: Option<u64>,
    pub(crate) stale_events: u64,
    pub(crate) readiness_failures: u64,
    pub(crate) crashes: u64,
    pub(crate) backoff_level: usize,
    pub(crate) unauthorized_bind_attempts: u64,
    pub(crate) association_commits: u64,
    pub(crate) association_removals: u64,
    pub(crate) cleanup_attempts: u64,
    pub(crate) cleanup_failures: u64,
    pub(crate) xwm_events_received: u64,
    pub(crate) xwm_drain_budget_exhaustions: u64,
    pub(crate) xwm_connection_failures: u64,
    pub(crate) resize_sync_started: u64,
    pub(crate) resize_sync_acks: u64,
    pub(crate) resize_sync_presented: u64,
    pub(crate) resize_sync_timeouts: u64,
    pub(crate) resize_sync_command_failures: u64,
    pub(crate) property_refresh_requested: u64,
    pub(crate) property_refresh_completed: u64,
    pub(crate) property_refresh_coalesced: u64,
    pub(crate) property_refresh_rejected: u64,
    pub(crate) property_refresh_stale: u64,
    pub(crate) stderr_bytes: u64,
    pub(crate) stderr_lines: u64,
    pub(crate) stderr_truncated: u64,
    pub(crate) stderr_closed: u64,
}
