use std::collections::HashMap;

use x11rb::protocol::xproto::Atom;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum XwmAtomName {
    WmS0,
    Manager,
    WlSurfaceSerial,
    Utf8String,
    WmProtocols,
    WmState,
    WmWindowRole,
    WmDeleteWindow,
    WmTakeFocus,
    WmHints,
    WmClass,
    WmName,
    WmClientLeader,
    WmTransientFor,
    WmNormalHints,
    NetWmName,
    NetStartupId,
    NetWmPid,
    NetWmUserTime,
    NetWmUserTimeWindow,
    NetWmWindowType,
    NetWmWindowTypeNormal,
    NetWmWindowTypeDialog,
    NetWmWindowTypeUtility,
    NetWmWindowTypeMenu,
    NetWmWindowTypePopupMenu,
    NetWmWindowTypeDropdownMenu,
    NetWmWindowTypeTooltip,
    NetWmWindowTypeNotification,
    NetWmWindowTypeCombo,
    NetWmWindowTypeSplash,
    NetWmWindowTypeToolbar,
    NetWmWindowTypeDock,
    NetWmWindowTypeDesktop,
    NetWmWindowTypeDnd,
    NetWmState,
    NetWmStateFullscreen,
    NetWmStateMaximizedVert,
    NetWmStateMaximizedHorz,
    NetWmStateHidden,
    NetWmStateDemandsAttention,
    NetActiveWindow,
    NetCloseWindow,
    NetMoveResizeWindow,
    NetWmMoveresize,
    NetSupported,
    NetSupportingWmCheck,
    NetClientList,
    NetClientListStacking,
    NetNumberOfDesktops,
    NetCurrentDesktop,
    NetDesktopGeometry,
    NetDesktopViewport,
    NetWorkarea,
    NetFrameExtents,
    WmChangeState,
    NetWmSyncRequest,
    NetWmSyncRequestCounter,
    XwaylandAllowCommits,
    MotifWmHints,
    NetWmNameTyphon,
}

impl XwmAtomName {
    pub(crate) const ALL: &'static [Self] = &[
        Self::WmS0,
        Self::Manager,
        Self::WlSurfaceSerial,
        Self::Utf8String,
        Self::WmProtocols,
        Self::WmState,
        Self::WmWindowRole,
        Self::WmDeleteWindow,
        Self::WmTakeFocus,
        Self::WmHints,
        Self::WmClass,
        Self::WmName,
        Self::WmClientLeader,
        Self::WmTransientFor,
        Self::WmNormalHints,
        Self::NetWmName,
        Self::NetStartupId,
        Self::NetWmPid,
        Self::NetWmUserTime,
        Self::NetWmUserTimeWindow,
        Self::NetWmWindowType,
        Self::NetWmWindowTypeNormal,
        Self::NetWmWindowTypeDialog,
        Self::NetWmWindowTypeUtility,
        Self::NetWmWindowTypeMenu,
        Self::NetWmWindowTypePopupMenu,
        Self::NetWmWindowTypeDropdownMenu,
        Self::NetWmWindowTypeTooltip,
        Self::NetWmWindowTypeNotification,
        Self::NetWmWindowTypeCombo,
        Self::NetWmWindowTypeSplash,
        Self::NetWmWindowTypeToolbar,
        Self::NetWmWindowTypeDock,
        Self::NetWmWindowTypeDesktop,
        Self::NetWmWindowTypeDnd,
        Self::NetWmState,
        Self::NetWmStateFullscreen,
        Self::NetWmStateMaximizedVert,
        Self::NetWmStateMaximizedHorz,
        Self::NetWmStateHidden,
        Self::NetWmStateDemandsAttention,
        Self::NetActiveWindow,
        Self::NetCloseWindow,
        Self::NetMoveResizeWindow,
        Self::NetWmMoveresize,
        Self::NetSupported,
        Self::NetSupportingWmCheck,
        Self::NetClientList,
        Self::NetClientListStacking,
        Self::NetNumberOfDesktops,
        Self::NetCurrentDesktop,
        Self::NetDesktopGeometry,
        Self::NetDesktopViewport,
        Self::NetWorkarea,
        Self::NetFrameExtents,
        Self::WmChangeState,
        Self::NetWmSyncRequest,
        Self::NetWmSyncRequestCounter,
        Self::XwaylandAllowCommits,
        Self::MotifWmHints,
        Self::NetWmNameTyphon,
    ];

    pub(crate) const fn as_bytes(self) -> &'static [u8] {
        match self {
            Self::WmS0 => b"WM_S0",
            Self::Manager => b"MANAGER",
            Self::WlSurfaceSerial => b"WL_SURFACE_SERIAL",
            Self::Utf8String => b"UTF8_STRING",
            Self::WmProtocols => b"WM_PROTOCOLS",
            Self::WmState => b"WM_STATE",
            Self::WmWindowRole => b"WM_WINDOW_ROLE",
            Self::WmDeleteWindow => b"WM_DELETE_WINDOW",
            Self::WmTakeFocus => b"WM_TAKE_FOCUS",
            Self::WmHints => b"WM_HINTS",
            Self::WmClass => b"WM_CLASS",
            Self::WmName => b"WM_NAME",
            Self::WmClientLeader => b"WM_CLIENT_LEADER",
            Self::WmTransientFor => b"WM_TRANSIENT_FOR",
            Self::WmNormalHints => b"WM_NORMAL_HINTS",
            Self::NetWmName => b"_NET_WM_NAME",
            Self::NetStartupId => b"_NET_STARTUP_ID",
            Self::NetWmPid => b"_NET_WM_PID",
            Self::NetWmUserTime => b"_NET_WM_USER_TIME",
            Self::NetWmUserTimeWindow => b"_NET_WM_USER_TIME_WINDOW",
            Self::NetWmWindowType => b"_NET_WM_WINDOW_TYPE",
            Self::NetWmWindowTypeNormal => b"_NET_WM_WINDOW_TYPE_NORMAL",
            Self::NetWmWindowTypeDialog => b"_NET_WM_WINDOW_TYPE_DIALOG",
            Self::NetWmWindowTypeUtility => b"_NET_WM_WINDOW_TYPE_UTILITY",
            Self::NetWmWindowTypeMenu => b"_NET_WM_WINDOW_TYPE_MENU",
            Self::NetWmWindowTypePopupMenu => b"_NET_WM_WINDOW_TYPE_POPUP_MENU",
            Self::NetWmWindowTypeDropdownMenu => b"_NET_WM_WINDOW_TYPE_DROPDOWN_MENU",
            Self::NetWmWindowTypeTooltip => b"_NET_WM_WINDOW_TYPE_TOOLTIP",
            Self::NetWmWindowTypeNotification => b"_NET_WM_WINDOW_TYPE_NOTIFICATION",
            Self::NetWmWindowTypeCombo => b"_NET_WM_WINDOW_TYPE_COMBO",
            Self::NetWmWindowTypeSplash => b"_NET_WM_WINDOW_TYPE_SPLASH",
            Self::NetWmWindowTypeToolbar => b"_NET_WM_WINDOW_TYPE_TOOLBAR",
            Self::NetWmWindowTypeDock => b"_NET_WM_WINDOW_TYPE_DOCK",
            Self::NetWmWindowTypeDesktop => b"_NET_WM_WINDOW_TYPE_DESKTOP",
            Self::NetWmWindowTypeDnd => b"_NET_WM_WINDOW_TYPE_DND",
            Self::NetWmState => b"_NET_WM_STATE",
            Self::NetWmStateFullscreen => b"_NET_WM_STATE_FULLSCREEN",
            Self::NetWmStateMaximizedVert => b"_NET_WM_STATE_MAXIMIZED_VERT",
            Self::NetWmStateMaximizedHorz => b"_NET_WM_STATE_MAXIMIZED_HORZ",
            Self::NetWmStateHidden => b"_NET_WM_STATE_HIDDEN",
            Self::NetWmStateDemandsAttention => b"_NET_WM_STATE_DEMANDS_ATTENTION",
            Self::NetActiveWindow => b"_NET_ACTIVE_WINDOW",
            Self::NetCloseWindow => b"_NET_CLOSE_WINDOW",
            Self::NetMoveResizeWindow => b"_NET_MOVERESIZE_WINDOW",
            Self::NetWmMoveresize => b"_NET_WM_MOVERESIZE",
            Self::NetSupported => b"_NET_SUPPORTED",
            Self::NetSupportingWmCheck => b"_NET_SUPPORTING_WM_CHECK",
            Self::NetClientList => b"_NET_CLIENT_LIST",
            Self::NetClientListStacking => b"_NET_CLIENT_LIST_STACKING",
            Self::NetNumberOfDesktops => b"_NET_NUMBER_OF_DESKTOPS",
            Self::NetCurrentDesktop => b"_NET_CURRENT_DESKTOP",
            Self::NetDesktopGeometry => b"_NET_DESKTOP_GEOMETRY",
            Self::NetDesktopViewport => b"_NET_DESKTOP_VIEWPORT",
            Self::NetWorkarea => b"_NET_WORKAREA",
            Self::NetFrameExtents => b"_NET_FRAME_EXTENTS",
            Self::WmChangeState => b"WM_CHANGE_STATE",
            Self::NetWmSyncRequest => b"_NET_WM_SYNC_REQUEST",
            Self::NetWmSyncRequestCounter => b"_NET_WM_SYNC_REQUEST_COUNTER",
            Self::XwaylandAllowCommits => b"_XWAYLAND_ALLOW_COMMITS",
            Self::MotifWmHints => b"_MOTIF_WM_HINTS",
            Self::NetWmNameTyphon => b"Typhon",
        }
    }
}

#[derive(Debug, Default)]
pub(crate) struct XwmAtoms {
    values: HashMap<XwmAtomName, Atom>,
}

impl XwmAtoms {
    pub(crate) fn from_values(values: HashMap<XwmAtomName, Atom>) -> Self {
        Self { values }
    }

    pub(crate) fn into_values(self) -> HashMap<XwmAtomName, Atom> {
        self.values
    }

    pub(crate) fn get(&self, name: XwmAtomName) -> Atom {
        self.values
            .get(&name)
            .copied()
            .expect("all required XWM atoms are interned")
    }

    pub(crate) fn advertised_names() -> &'static [XwmAtomName] {
        &[
            XwmAtomName::NetSupported,
            XwmAtomName::NetSupportingWmCheck,
            XwmAtomName::NetWmName,
            XwmAtomName::NetWmPid,
            XwmAtomName::NetWmWindowType,
            XwmAtomName::NetActiveWindow,
            XwmAtomName::NetClientList,
            XwmAtomName::NetClientListStacking,
            XwmAtomName::NetNumberOfDesktops,
            XwmAtomName::NetCurrentDesktop,
            XwmAtomName::NetDesktopGeometry,
            XwmAtomName::NetDesktopViewport,
            XwmAtomName::NetWorkarea,
            XwmAtomName::NetFrameExtents,
            XwmAtomName::WmChangeState,
            XwmAtomName::NetCloseWindow,
            XwmAtomName::NetWmState,
            XwmAtomName::NetWmStateFullscreen,
            XwmAtomName::NetWmStateMaximizedVert,
            XwmAtomName::NetWmStateMaximizedHorz,
            XwmAtomName::NetWmStateHidden,
            XwmAtomName::NetWmSyncRequest,
        ]
    }
}
