mod activation;
mod advanced;
mod buffers;
mod core;
mod data_device;
mod globals;
mod input;
mod layer_shell;
mod presentation;
mod shell_control;
mod shortcuts;
mod syncobj;
pub(crate) mod versions;
mod viewport;
mod xdg;
mod xwayland;
