mod activation;
mod advanced;
mod buffers;
mod commit_timing;
mod core;
pub(crate) mod cursor_shape;
mod data_control;
mod data_device;
mod fifo;
mod globals;
mod idle_inhibit;
mod input;
mod keyboard_shortcuts_inhibit;
mod layer_shell;
mod presentation;
mod presentation_modes;
mod primary_selection;
mod shell_auth;
mod shell_control;
mod shortcuts;
mod syncobj;
mod toplevel_management;
pub(crate) mod versions;
mod viewport;
mod xdg;
mod xwayland;
