name: Rust

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
      - run: cargo fmt --check
      - run: cargo check --all-targets
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test
      - run: ./bin/check-source-layout
